<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Projects</name>
   <tag></tag>
   <elementGuidId>971b644e-14dc-493a-a326-64fa176aac46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select__control.select__control--is-focused.select__control--menu-is-open.css-x00jme-control > div.select__value-container.css-1hwfws3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='employee']/div/div)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__value-container css-1hwfws3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Projects</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/main[@class=&quot;animated fadeIn&quot;]/section[@class=&quot;tab-content-section&quot;]/div[@class=&quot;container mw-lg px-lg-up-0&quot;]/div[@class=&quot;tab-content-wrapper&quot;]/div[@class=&quot;tab-content visible&quot;]/form[1]/div[@class=&quot;row row-3 mb-3 mb-md-4&quot;]/div[@class=&quot;col-md-4 col-12&quot;]/div[@class=&quot;form-group d-flex align-items-center&quot;]/div[@id=&quot;employee&quot;]/div[@class=&quot;select__control select__control--is-focused select__control--menu-is-open css-x00jme-control&quot;]/div[@class=&quot;select__value-container css-1hwfws3&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='employee']/div/div)[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residential'])[8]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BSD City'])[14]/following::div[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ImajiHaus'])[1]/preceding::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
